Tags = sorted(['FPS', 'Shooter', 'Multiplayer', 'Competitive', 'Action', 'Team-Based', 'eSports', 'Tactical', 'First-Person', 'PvP', 
        'Online Co-Op', 'Co-op', 'Strategy', 'Military', 'War', 'Difficult', 'Trading', 'Realistic', 'Fast-Paced', 'Moddable', 
        'Free to Play', 'MOBA', 'RTS', 'RPG', 'Tower Defense', 'Fantasy', 'Character Customization', 'Replay Value', 'Action RPG', 
        'Simulation', 'Hunting', 'Dating Sim', 'Dragons', 'Open World', 'Third Person', 'Adventure', 'Cute', 'Singleplayer', 'Atmospheric', 
        'Great Soundtrack', 'Underwater', 'Souls-like', 'Hero Shooter', 'Third-Person Shooter', 'Superhero', '3D', 'Sci-fi', 'Sexual Content', 
        'Cyberpunk', 'Survival', 'Battle Royale', 'Early Access', 'Stealth', 'Crafting', 'Open World Survival Craft', 'Building', 'Sandbox', 
        'Nudity', 'Indie', 'Post-apocalyptic', 'Clicker', '2D', 'Casual', 'Family Friendly', 'Idler', 'Funny', 'Colorful', 'Arcade', 'Hidden Object',
        'Pixel Graphics', 'Mystery', 'Anime', 'Horror', 'Comedy', 'Physics', 'Action Roguelike', 'Procedural Generation', 'Perma Death', 'Exploration',
        'Robots', 'Dystopian', 'Destruction', 'Stylized', 'Futuristic', 'Combat', 'LGBTQ+', 'Loot', 'Lore-Rich', 'Cinematic', 'Sports',
        'Football (Soccer)', 'Controller', 'Local Co-Op', 'Local Multiplayer', 'Modern', 'Soundtrack', 'Split Screen', 'Crime', 'Automobile Sim',
        'Mature', 'Racing', 'Violent', 'Story Rich', 'Gore', 'Choices Matter', 'Turn-Based Combat', 'Dungeons & Dragons', 'CRPG', 'Romance',
        'Co-op Campaign', 'Class-Based', 'Dark Fantasy', 'Management', 'Economy', 'Real Time Tactics', 'Text-Based', 'Games Workshop', 'Cartoony',
        'Cartoon', 'Vehicular Combat', 'World War II', 'VR', 'Flight', 'Tanks', 'Naval Combat', 'Massively Multiplayer', 'Cold War',
        'Looter Shooter', 'MMORPG', 'PvE', 'Space', 'Utilities', 'Software', 'Game Development', 'Design & Illustration', 'Animation & Modeling',
        'Photo Editing', 'Education', 'Hack and Slash', 'Parkour', 'Ninja', 'NSFW', 'Memes', 'Gaming', 'Farming Sim', 'Life Sim',
        'Relaxing', 'Agriculture', 'Fishing', 'Zombies', 'Survival Horror', 'Choose Your Own Adventure', 'Psychological Horror',
        'Platformer', 'Runner', '3D Platformer', 'Medieval', 'Historical', 'Political', 'Swordplay', 'Immersive', 'Alternate History',
        'Action-Adventure', 'Emotional', 'Extraction Shooter', 'Immersive Sim', 'Grand Strategy', 'Real-Time with Pause', 'Diplomacy',
        'Strategy RPG', 'Blood', 'Capitalism', 'Female Protagonist', 'Puzzle Platformer', 'Politics', 'Isometric', 'Dungeon Crawler',
        'Inventory Management', 'Dark', 'Football (American)', '4 Player Local', 'Magic', 'Classic', 'Remake', 'Walking Simulator',
        'Turn-Based Strategy', 'Turn-Based', '4X', 'City Builder', 'Hex Grid', 'Dark Humor', 'Base Building', 'Voxel', 'Mod', 'Card Game',
        'Roguelike Deckbuilder', 'Roguelike', 'Deckbuilding', 'Roguelite', 'Card Battler', 'Mythology', 'Creature Collector', 'Automation',
        'Dinosaurs', 'Western', 'Horses', 'Beautiful', 'Driving', 'Transportation', 'Colony Sim', 'Tactical RPG', 'Supernatural',
        'Investigation', 'Demons', 'Detective', 'Thriller', 'Political Sim', 'Turn-Based Tactics', 'Dwarf', 'JRPG', 'Resource Management',
        'Trains', 'Cooking', 'Real-Time', 'Skateboarding', 'Audio Production', 'Music', 'Psychological', 'Trading Card Game', 'Time Management',
        'Nature', 'Farming', 'Martial Arts', 'Foreign', 'Level Editor', 'Precision Platformer', 'Rhythm', 'Side Scroller',
        'Kickstarter', 'Crowdfunded', 'Addictive', 'Touch-Friendly', 'Wargame', 'Nonlinear', 'Basketball',
        'Visual Novel', 'Old School', 'Fighting', '2D Fighter', '2D Platformer', 'Cats', 'Typing', '1980s',
        'Collectathon', 'Arena Shooter', 'Mouse only', '3D Vision', 'TrackIR', 'Artificial Intelligence',
        'Multiple Endings', 'Video Production', 'Web Publishing', 'Psychedelic', 'Naval', 'Space Sim',
        "1990's", 'Score Attack', 'Assassin', 'Nostalgia', 'Aliens', 'Pirates', 'Sailing', 'GameMaker',
        'Hentai', 'Puzzle', 'Heist', 'Gun Customization', 'America', 'Warhammer 40K', 'Narration',
        'Gambling', 'Mining', 'God Game', 'Minimalist', 'Time Manipulation', 'Action RTS', 'Tutorial',
        'Party-Based RPG', 'World War I', 'Dark Comedy', 'Auto Battler', 'Bullet Hell', 'Mechs',
        '6DOF', 'Tabletop', 'Board Game', 'Hand-drawn', 'Boomer Shooter', 'Character Action Game',
        'Spectacle fighter', 'Retro', '3D Fighter', 'Software Training', 'Spaceships', 'Metroidvania',
        'Drama', 'Social Deduction', 'Party Game', 'Top-Down', 'Minigames'])

Genres = sorted(['Action', 'Free To Play', 'Strategy', 'Adventure', 'RPG', 'Massively Multiplayer', 'Indie', 'Casual', 'Simulation', 
          'Early Access', 'Sports', 'Racing', 'Animation & Modeling', 'Design & Illustration', 'Education', 'Photo Editing', 
          'Utilities', 'Game Development', 'Audio Production', 'Video Production', 'Software Training'])

